### ISSUE TITLE
Create a doc which gives 'brand guidelines' for the installation docs

### ISSUE THREAD

**Issue by zackbloom** [EagerIO/EmbedBox#22] opened 2016-07-27 18:20 UTC
I'm thinking things like the max size of screenshots, the nature and color of arrows, etc.

**Comment by adamschwartz** [comment] 2016-07-27 18:44
lol https://github.com/EagerIO/EmbedBox/issues/25 great minds

**Comment by TeffenEllis** [comment] 2016-08-04 12:58
Duplicate of #25  :)

**Closed by TeffenEllis** 2016-08-04 12:58 UTC
